version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: challenge_titan_os_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: challenge_titan_os_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - challenge_titan_os_network

  # Aplicación Rails
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: challenge_titan_os_web
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/challenge_titan_os_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 2
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    networks:
      - challenge_titan_os_network
    command: ./bin/dev

volumes:
  postgres_data:
    driver: local
  bundle_cache:
    driver: local

networks:
  challenge_titan_os_network:
    driver: bridge
